empty('x').
num('a').
num('b').
num('c').
num('d').
num('e').
num('f').
num('g').
num('h').
num('i').
atom_list_concat([H|T], Cat):-
    atom_list_concat(H,T,Cat).
atom_list_concat(Cat,[],Cat).
atom_list_concat(A,[H|T],Cat) :-
    atom_concat(A,H,ACat),
    atom_list_concat(ACat,T,Cat).
main([_|H]):-
    write("Input:<"),
    write(H),
    write(">Answer:<"),
    (H=[Arg|_],solver(Arg);write("false")),
    write(">").

solver(Sample) :-
    (not(atom(Sample))->fail;atom_length(Sample,Length)),
    (Length>0->(sub_atom(Sample, 0,1,_,AAE),not(empty(AAE))->AA=AAE;num(AA));num(AA)),
    
    (Length>1->(sub_atom(Sample, 1,1,_,ABE),not(empty(ABE))->AB=ABE;num(AB));num(AB)),
    AB\=AA,
    (Length>2->(sub_atom(Sample, 2,1,_,ACE),not(empty(ACE))->AC=ACE;num(AC));num(AC)),
    AC\=AA,AC\=AB,
    (Length>3->(sub_atom(Sample, 3,1,_,ADE),not(empty(ADE))->AD=ADE;num(AD));num(AD)),
    AD\=AA,AD\=AB,AD\=AC,
    (Length>4->(sub_atom(Sample, 4,1,_,AEE),not(empty(AEE))->AE=AEE;num(AE));num(AE)),
    AE\=AA,AE\=AB,AE\=AC,AE\=AD,
    (Length>5->(sub_atom(Sample, 5,1,_,AFE),not(empty(AFE))->AF=AFE;num(AF));num(AF)),
    AF\=AA,AF\=AB,AF\=AC,AF\=AD,AF\=AE,
    (Length>6->(sub_atom(Sample, 6,1,_,AGE),not(empty(AGE))->AG=AGE;num(AG));num(AG)),
    AG\=AA,AG\=AB,AG\=AC,AG\=AD,AG\=AE,AG\=AF,
    (Length>7->(sub_atom(Sample, 7,1,_,AHE),not(empty(AHE))->AH=AHE;num(AH));num(AH)),
    AH\=AA,AH\=AB,AH\=AC,AH\=AD,AH\=AE,AH\=AF,AH\=AG,
    (Length>8->(sub_atom(Sample, 8,1,_,AIE),not(empty(AIE))->AI=AIE;num(AI));num(AI)),
    AI\=AA,AI\=AB,AI\=AC,AI\=AD,AI\=AE,AI\=AF,AI\=AG,AI\=AH,
    
    (Length>9->(sub_atom(Sample, 9,1,_,BAE),not(empty(BAE))->BA=BAE;num(BA));num(BA)),
    BA\=AA,BA\=AB,BA\=AC,
    (Length>10->(sub_atom(Sample, 10,1,_,BBE),not(empty(BBE))->BB=BBE;num(BB));num(BB)),
    BB\=BA,BB\=AB,BB\=AA,BB\=AC,
    (Length>11->(sub_atom(Sample, 11,1,_,BCE),not(empty(BCE))->BC=BCE;num(BC));num(BC)),
    BC\=BA,BC\=BB,BC\=AC,BC\=AA,BC\=AB,
    (Length>12->(sub_atom(Sample, 12,1,_,BDE),not(empty(BDE))->BD=BDE;num(BD));num(BD)),
    BD\=BA,BD\=BB,BD\=BC,BD\=AD,BD\=AE,BD\=AF,
    (Length>13->(sub_atom(Sample, 13,1,_,BEE),not(empty(BEE))->BE=BEE;num(BE));num(BE)),
    BE\=BA,BE\=BB,BE\=BC,BE\=BD,BE\=AE,BE\=AD,BE\=AF,
    (Length>14->(sub_atom(Sample, 14,1,_,BFE),not(empty(BFE))->BF=BFE;num(BF));num(BF)),
    BF\=BA,BF\=BB,BF\=BC,BF\=BD,BF\=BE,BF\=AF,BF\=AD,BF\=AE,
    (Length>15->(sub_atom(Sample, 15,1,_,BGE),not(empty(BGE))->BG=BGE;num(BG));num(BG)),
    BG\=BA,BG\=BB,BG\=BC,BG\=BD,BG\=BE,BG\=BF,BG\=AG,BG\=AH,BG\=AI,
    (Length>16->(sub_atom(Sample, 16,1,_,BHE),not(empty(BHE))->BH=BHE;num(BH));num(BH)),
    BH\=BA,BH\=BB,BH\=BC,BH\=BD,BH\=BE,BH\=BF,BH\=BG,BH\=AH,BH\=AI,BH\=AG,
    (Length>17->(sub_atom(Sample, 17,1,_,BIE),not(empty(BIE))->BI=BIE;num(BI));num(BI)),
    BI\=BA,BI\=BB,BI\=BC,BI\=BD,BI\=BE,BI\=BF,BI\=BG,BI\=BH,BI\=AI,BI\=AG,BI\=AH,
    
    (Length>18->(sub_atom(Sample, 18,1,_,CAE),not(empty(CAE))->CA=CAE;num(CA));num(CA)),
    CA\=AA,CA\=BA,CA\=AB,CA\=BB,CA\=AC,CA\=BC,
    (Length>19->(sub_atom(Sample, 19,1,_,CBE),not(empty(CBE))->CB=CBE;num(CB));num(CB)),
    CB\=CA,CB\=AB,CB\=BB,CB\=AA,CB\=BA,CB\=AC,CB\=BC,
    (Length>20->(sub_atom(Sample, 20,1,_,CCE),not(empty(CCE))->CC=CCE;num(CC));num(CC)),
    CC\=CA,CC\=CB,CC\=AC,CC\=BC,CC\=AA,CC\=BB,CC\=BA,CC\=AB,
    (Length>21->(sub_atom(Sample, 21,1,_,CDE),not(empty(CDE))->CD=CDE;num(CD));num(CD)),
    CD\=CA,CD\=CB,CD\=CC,CD\=AD,CD\=BD,CD\=AE,CD\=BE,CD\=AF,CD\=BF,
    (Length>22->(sub_atom(Sample, 22,1,_,CEE),not(empty(CEE))->CE=CEE;num(CE));num(CE)),
    CE\=CA,CE\=CB,CE\=CC,CE\=CD,CE\=AE,CE\=BE,CE\=AD,CE\=BD,CE\=AF,CE\=BF,
    (Length>23->(sub_atom(Sample, 23,1,_,CFE),not(empty(CFE))->CF=CFE;num(CF));num(CF)),
    CF\=CA,CF\=CB,CF\=CC,CF\=CD,CF\=CE,CF\=AF,CF\=BF,CF\=AD,CF\=BD,CF\=AE,CF\=BE,
    (Length>24->(sub_atom(Sample, 24,1,_,CGE),not(empty(CGE))->CG=CGE;num(CG));num(CG)),
    CG\=CA,CG\=CB,CG\=CC,CG\=CD,CG\=CE,CG\=CF,CG\=AG,CG\=BG,CG\=BH,CG\=AI,CG\=AH,CG\=BI,
    (Length>25->(sub_atom(Sample, 25,1,_,CHE),not(empty(CHE))->CH=CHE;num(CH));num(CH)),
    CH\=CA,CH\=CB,CH\=CC,CH\=CD,CH\=CE,CH\=CF,CH\=CG,CH\=AH,CH\=BH,CH\=AG,CH\=BG,CH\=AI,CH\=BI,
    (Length>26->(sub_atom(Sample, 26,1,_,CIE),not(empty(CIE))->CI=CIE;num(CI));num(CI)),
    CI\=CA,CI\=CB,CI\=CC,CI\=CD,CI\=CE,CI\=CF,CI\=CG,CI\=CH,CI\=AI,CI\=BI,CI\=AG,CI\=BG,CI\=AH,CI\=BH,
    
    (Length>27->(sub_atom(Sample, 27,1,_,DAE),not(empty(DAE))->DA=DAE;num(DA));num(DA)),
    DA\=AA,DA\=BA,DA\=CA,
    (Length>28->(sub_atom(Sample, 28,1,_,DBE),not(empty(DBE))->DB=DBE;num(DB));num(DB)),
    DB\=DA,DB\=AB,DB\=BB,DB\=CB,
    (Length>29->(sub_atom(Sample, 29,1,_,DCE),not(empty(DCE))->DC=DCE;num(DC));num(DC)),
    DC\=DA,DC\=DB,DC\=AC,DC\=BC,DC\=CC,
    (Length>30->(sub_atom(Sample, 30,1,_,DDE),not(empty(DDE))->DD=DDE;num(DD));num(DD)),
    DD\=DA,DD\=DB,DD\=DC,DD\=AD,DD\=BD,DD\=CD,DD\=AA,DD\=BB,DD\=CC,
    (Length>31->(sub_atom(Sample, 31,1,_,DEE),not(empty(DEE))->DE=DEE;num(DE));num(DE)),
    DE\=DA,DE\=DB,DE\=DC,DE\=DD,DE\=AE,DE\=BE,DE\=CE,
    (Length>32->(sub_atom(Sample, 32,1,_,DFE),not(empty(DFE))->DF=DFE;num(DF));num(DF)),
    DF\=DA,DF\=DB,DF\=DC,DF\=DD,DF\=DE,DF\=AF,DF\=BF,DF\=CF,DF\=CG,DF\=BH,DF\=AI,
    (Length>33->(sub_atom(Sample, 33,1,_,DGE),not(empty(DGE))->DG=DGE;num(DG));num(DG)),
    DG\=DA,DG\=DB,DG\=DC,DG\=DD,DG\=DE,DG\=DF,DG\=AG,DG\=BG,DG\=CG,
    (Length>34->(sub_atom(Sample, 34,1,_,DHE),not(empty(DHE))->DH=DHE;num(DH));num(DH)),
    DH\=DA,DH\=DB,DH\=DC,DH\=DD,DH\=DE,DH\=DF,DH\=DG,DH\=AH,DH\=BH,DH\=CH,
    (Length>35->(sub_atom(Sample, 35,1,_,DIE),not(empty(DIE))->DI=DIE;num(DI));num(DI)),
    DI\=DA,DI\=DB,DI\=DC,DI\=DD,DI\=DE,DI\=DF,DI\=DG,DI\=DH,DI\=AI,DI\=BI,DI\=CI,
    
    (Length>36->(sub_atom(Sample, 36,1,_,EAE),not(empty(EAE))->EA=EAE;num(EA));num(EA)),
    EA\=AA,EA\=BA,EA\=CA,EA\=DA,EA\=DB,EA\=DC,
    (Length>37->(sub_atom(Sample, 37,1,_,EBE),not(empty(EBE))->EB=EBE;num(EB));num(EB)),
    EB\=EA,EB\=AB,EB\=BB,EB\=CB,EB\=DB,EB\=DA,EB\=DC,
    (Length>38->(sub_atom(Sample, 38,1,_,ECE),not(empty(ECE))->EC=ECE;num(EC));num(EC)),
    EC\=EA,EC\=EB,EC\=AC,EC\=BC,EC\=CC,EC\=DC,EC\=DA,EC\=DB,
    (Length>39->(sub_atom(Sample, 39,1,_,EDE),not(empty(EDE))->ED=EDE;num(ED));num(ED)),
    ED\=EA,ED\=EB,ED\=EC,ED\=AD,ED\=BD,ED\=CD,ED\=DD,ED\=DE,ED\=DF,
    (Length>40->(sub_atom(Sample, 40,1,_,EEE),not(empty(EEE))->EE=EEE;num(EE));num(EE)),
    EE\=EA,EE\=EB,EE\=EC,EE\=ED,EE\=AE,EE\=BE,EE\=CE,EE\=DE,EE\=AA,EE\=BB,EE\=CC,EE\=DD,EE\=DF,EE\=CG,EE\=BH,EE\=AI,
    (Length>41->(sub_atom(Sample, 41,1,_,EFE),not(empty(EFE))->EF=EFE;num(EF));num(EF)),
    EF\=EA,EF\=EB,EF\=EC,EF\=ED,EF\=EE,EF\=AF,EF\=BF,EF\=CF,EF\=DF,EF\=DD,EF\=DE,
    (Length>42->(sub_atom(Sample, 42,1,_,EGE),not(empty(EGE))->EG=EGE;num(EG));num(EG)),
    EG\=EA,EG\=EB,EG\=EC,EG\=ED,EG\=EE,EG\=EF,EG\=AG,EG\=BG,EG\=CG,EG\=DG,EG\=DH,EG\=DI,
    (Length>43->(sub_atom(Sample, 43,1,_,EHE),not(empty(EHE))->EH=EHE;num(EH));num(EH)),
    EH\=EA,EH\=EB,EH\=EC,EH\=ED,EH\=EE,EH\=EF,EH\=EG,EH\=AH,EH\=BH,EH\=CH,EH\=DH,EH\=DG,EH\=DI,
    (Length>44->(sub_atom(Sample, 44,1,_,EIE),not(empty(EIE))->EI=EIE;num(EI));num(EI)),
    EI\=EA,EI\=EB,EI\=EC,EI\=ED,EI\=EE,EI\=EF,EI\=EG,EI\=EH,EI\=AI,EI\=BI,EI\=CI,EI\=DI,EI\=DG,EI\=DH,
    
    (Length>45->(sub_atom(Sample, 45,1,_,FAE),not(empty(FAE))->FA=FAE;num(FA));num(FA)),
    FA\=AA,FA\=BA,FA\=CA,FA\=DA,FA\=EA,FA\=DB,FA\=EB,FA\=DC,FA\=EC,
    (Length>46->(sub_atom(Sample, 46,1,_,FBE),not(empty(FBE))->FB=FBE;num(FB));num(FB)),
    FB\=FA,FB\=AB,FB\=BB,FB\=CB,FB\=DB,FB\=EB,FB\=DA,FB\=EA,FB\=DC,FB\=EC,
    (Length>47->(sub_atom(Sample, 47,1,_,FCE),not(empty(FCE))->FC=FCE;num(FC));num(FC)),
    FC\=FA,FC\=FB,FC\=AC,FC\=BC,FC\=CC,FC\=DC,FC\=EC,FC\=DA,FC\=EA,FC\=DB,FC\=EB,
    (Length>48->(sub_atom(Sample, 48,1,_,FDE),not(empty(FDE))->FD=FDE;num(FD));num(FD)),
    FD\=FA,FD\=FB,FD\=FC,FD\=AD,FD\=BD,FD\=CD,FD\=DD,FD\=ED,FD\=EE,FD\=DF,FD\=CG,FD\=BH,FD\=AI,FD\=DE,FD\=EF,
    (Length>49->(sub_atom(Sample, 49,1,_,FEE),not(empty(FEE))->FE=FEE;num(FE));num(FE)),
    FE\=FA,FE\=FB,FE\=FC,FE\=FD,FE\=AE,FE\=BE,FE\=CE,FE\=DE,FE\=EE,FE\=DD,FE\=ED,FE\=DF,FE\=EF,
    (Length>50->(sub_atom(Sample, 50,1,_,FFE),not(empty(FFE))->FF=FFE;num(FF));num(FF)),
    FF\=FA,FF\=FB,FF\=FC,FF\=FD,FF\=FE,FF\=AF,FF\=BF,FF\=CF,FF\=DF,FF\=EF,FF\=AA,FF\=BB,FF\=CC,FF\=DD,FF\=EE,FF\=ED,FF\=DE,
    (Length>51->(sub_atom(Sample, 51,1,_,FGE),not(empty(FGE))->FG=FGE;num(FG));num(FG)),
    FG\=FA,FG\=FB,FG\=FC,FG\=FD,FG\=FE,FG\=FF,FG\=AG,FG\=BG,FG\=CG,FG\=DG,FG\=EG,FG\=DH,FG\=EH,FG\=DI,FG\=EI,
    (Length>52->(sub_atom(Sample, 52,1,_,FHE),not(empty(FHE))->FH=FHE;num(FH));num(FH)),
    FH\=FA,FH\=FB,FH\=FC,FH\=FD,FH\=FE,FH\=FF,FH\=FG,FH\=AH,FH\=BH,FH\=CH,FH\=DH,FH\=EH,FH\=DG,FH\=EG,FH\=DI,FH\=EI,
    (Length>53->(sub_atom(Sample, 53,1,_,FIE),not(empty(FIE))->FI=FIE;num(FI));num(FI)),
    FI\=FA,FI\=FB,FI\=FC,FI\=FD,FI\=FE,FI\=FF,FI\=FG,FI\=FH,FI\=AI,FI\=BI,FI\=CI,FI\=DI,FI\=EI,FI\=DG,FI\=EG,FI\=DH,FI\=EH,
    
    (Length>54->(sub_atom(Sample, 54,1,_,GAE),not(empty(GAE))->GA=GAE;num(GA));num(GA)),
    GA\=AA,GA\=BA,GA\=CA,GA\=DA,GA\=EA,GA\=FA,
    (Length>55->(sub_atom(Sample, 55,1,_,GBE),not(empty(GBE))->GB=GBE;num(GB));num(GB)),
    GB\=GA,GB\=AB,GB\=BB,GB\=CB,GB\=DB,GB\=EB,GB\=FB,
    (Length>56->(sub_atom(Sample, 56,1,_,GCE),not(empty(GCE))->GC=GCE;num(GC));num(GC)),
    GC\=GA,GC\=GB,GC\=AC,GC\=BC,GC\=CC,GC\=DC,GC\=EC,GC\=FC,GC\=FD,GC\=EE,GC\=DF,GC\=CG,GC\=BH,GC\=AI,
    (Length>57->(sub_atom(Sample, 57,1,_,GDE),not(empty(GDE))->GD=GDE;num(GD));num(GD)),
    GD\=GA,GD\=GB,GD\=GC,GD\=AD,GD\=BD,GD\=CD,GD\=DD,GD\=ED,GD\=FD,
    (Length>58->(sub_atom(Sample, 58,1,_,GEE),not(empty(GEE))->GE=GEE;num(GE));num(GE)),
    GE\=GA,GE\=GB,GE\=GC,GE\=GD,GE\=AE,GE\=BE,GE\=CE,GE\=DE,GE\=EE,GE\=FE,
    (Length>59->(sub_atom(Sample, 59,1,_,GFE),not(empty(GFE))->GF=GFE;num(GF));num(GF)),
    GF\=GA,GF\=GB,GF\=GC,GF\=GD,GF\=GE,GF\=AF,GF\=BF,GF\=CF,GF\=DF,GF\=EF,GF\=FF,
    (Length>60->(sub_atom(Sample, 60,1,_,GGE),not(empty(GGE))->GG=GGE;num(GG));num(GG)),
    GG\=GA,GG\=GB,GG\=GC,GG\=GD,GG\=GE,GG\=GF,GG\=AG,GG\=BG,GG\=CG,GG\=DG,GG\=EG,GG\=FG,GG\=AA,GG\=BB,GG\=CC,GG\=DD,GG\=EE,GG\=FF,
    (Length>61->(sub_atom(Sample, 61,1,_,GHE),not(empty(GHE))->GH=GHE;num(GH));num(GH)),
    GH\=GA,GH\=GB,GH\=GC,GH\=GD,GH\=GE,GH\=GF,GH\=GG,GH\=AH,GH\=BH,GH\=CH,GH\=DH,GH\=EH,GH\=FH,
    (Length>62->(sub_atom(Sample, 62,1,_,GIE),not(empty(GIE))->GI=GIE;num(GI));num(GI)),
    GI\=GA,GI\=GB,GI\=GC,GI\=GD,GI\=GE,GI\=GF,GI\=GG,GI\=GH,GI\=AI,GI\=BI,GI\=CI,GI\=DI,GI\=EI,GI\=FI,
    
    (Length>63->(sub_atom(Sample, 63,1,_,HAE),not(empty(HAE))->HA=HAE;num(HA));num(HA)),
    HA\=AA,HA\=BA,HA\=CA,HA\=DA,HA\=EA,HA\=FA,HA\=GA,HA\=GB,HA\=GC,
    (Length>64->(sub_atom(Sample, 64,1,_,HBE),not(empty(HBE))->HB=HBE;num(HB));num(HB)),
    HB\=HA,HB\=AB,HB\=BB,HB\=CB,HB\=DB,HB\=EB,HB\=FB,HB\=GB,HB\=GC,HB\=FD,HB\=EE,HB\=DF,HB\=CG,HB\=BH,HB\=AI,HB\=GA,
    (Length>65->(sub_atom(Sample, 65,1,_,HCE),not(empty(HCE))->HC=HCE;num(HC));num(HC)),
    HC\=HA,HC\=HB,HC\=AC,HC\=BC,HC\=CC,HC\=DC,HC\=EC,HC\=FC,HC\=GC,HC\=GA,HC\=GB,
    (Length>66->(sub_atom(Sample, 66,1,_,HDE),not(empty(HDE))->HD=HDE;num(HD));num(HD)),
    HD\=HA,HD\=HB,HD\=HC,HD\=AD,HD\=BD,HD\=CD,HD\=DD,HD\=ED,HD\=FD,HD\=GD,HD\=GE,HD\=GF,
    (Length>67->(sub_atom(Sample, 67,1,_,HEE),not(empty(HEE))->HE=HEE;num(HE));num(HE)),
    HE\=HA,HE\=HB,HE\=HC,HE\=HD,HE\=AE,HE\=BE,HE\=CE,HE\=DE,HE\=EE,HE\=FE,HE\=GE,HE\=GD,HE\=GF,
    (Length>68->(sub_atom(Sample, 68,1,_,HFE),not(empty(HFE))->HF=HFE;num(HF));num(HF)),
    HF\=HA,HF\=HB,HF\=HC,HF\=HD,HF\=HE,HF\=AF,HF\=BF,HF\=CF,HF\=DF,HF\=EF,HF\=FF,HF\=GF,HF\=GD,HF\=GE,
    (Length>69->(sub_atom(Sample, 69,1,_,HGE),not(empty(HGE))->HG=HGE;num(HG));num(HG)),
    HG\=HA,HG\=HB,HG\=HC,HG\=HD,HG\=HE,HG\=HF,HG\=AG,HG\=BG,HG\=CG,HG\=DG,HG\=EG,HG\=FG,HG\=GG,HG\=GH,HG\=GI,
    (Length>70->(sub_atom(Sample, 70,1,_,HHE),not(empty(HHE))->HH=HHE;num(HH));num(HH)),
    HH\=HA,HH\=HB,HH\=HC,HH\=HD,HH\=HE,HH\=HF,HH\=HG,HH\=AH,HH\=BH,HH\=CH,HH\=DH,HH\=EH,HH\=FH,HH\=GH,HH\=AA,HH\=BB,HH\=CC,HH\=DD,HH\=EE,HH\=FF,HH\=GG,HH\=GI,
    (Length>71->(sub_atom(Sample, 71,1,_,HIE),not(empty(HIE))->HI=HIE;num(HI));num(HI)),
    HI\=HA,HI\=HB,HI\=HC,HI\=HD,HI\=HE,HI\=HF,HI\=HG,HI\=HH,HI\=AI,HI\=BI,HI\=CI,HI\=DI,HI\=EI,HI\=FI,HI\=GI,HI\=GG,HI\=GH,
    
    (Length>72->(sub_atom(Sample, 72,1,_,IAE),not(empty(IAE))->IA=IAE;num(IA));num(IA)),
    IA\=AA,IA\=BA,IA\=CA,IA\=DA,IA\=EA,IA\=FA,IA\=GA,IA\=HA,IA\=HB,IA\=GC,IA\=FD,IA\=EE,IA\=DF,IA\=CG,IA\=BH,IA\=AI,IA\=GB,IA\=HC,
    (Length>73->(sub_atom(Sample, 73,1,_,IBE),not(empty(IBE))->IB=IBE;num(IB));num(IB)),
    IB\=IA,IB\=AB,IB\=BB,IB\=CB,IB\=DB,IB\=EB,IB\=FB,IB\=GB,IB\=HB,IB\=GA,IB\=HA,IB\=GC,IB\=HC,
    (Length>74->(sub_atom(Sample, 74,1,_,ICE),not(empty(ICE))->IC=ICE;num(IC));num(IC)),
    IC\=IA,IC\=IB,IC\=AC,IC\=BC,IC\=CC,IC\=DC,IC\=EC,IC\=FC,IC\=GC,IC\=HC,IC\=GA,IC\=HA,IC\=GB,IC\=HB,
    (Length>75->(sub_atom(Sample, 75,1,_,IDE),not(empty(IDE))->ID=IDE;num(ID));num(ID)),
    ID\=IA,ID\=IB,ID\=IC,ID\=AD,ID\=BD,ID\=CD,ID\=DD,ID\=ED,ID\=FD,ID\=GD,ID\=HD,ID\=GE,ID\=HE,ID\=GF,ID\=HF,
    (Length>76->(sub_atom(Sample, 76,1,_,IEE),not(empty(IEE))->IE=IEE;num(IE));num(IE)),
    IE\=IA,IE\=IB,IE\=IC,IE\=ID,IE\=AE,IE\=BE,IE\=CE,IE\=DE,IE\=EE,IE\=FE,IE\=GE,IE\=HE,IE\=GD,IE\=HD,IE\=GF,IE\=HF,
    (Length>77->(sub_atom(Sample, 77,1,_,IFE),not(empty(IFE))->IF=IFE;num(IF));num(IF)),
    IF\=IA,IF\=IB,IF\=IC,IF\=ID,IF\=IE,IF\=AF,IF\=BF,IF\=CF,IF\=DF,IF\=EF,IF\=FF,IF\=GF,IF\=HF,IF\=GD,IF\=HD,IF\=GE,IF\=HE,
    (Length>78->(sub_atom(Sample, 78,1,_,IGE),not(empty(IGE))->IG=IGE;num(IG));num(IG)),
    IG\=IA,IG\=IB,IG\=IC,IG\=ID,IG\=IE,IG\=IF,IG\=AG,IG\=BG,IG\=CG,IG\=DG,IG\=EG,IG\=FG,IG\=GG,IG\=HG,IG\=GH,IG\=HH,IG\=GI,IG\=HI,
    (Length>79->(sub_atom(Sample, 79,1,_,IHE),not(empty(IHE))->IH=IHE;num(IH));num(IH)),
    IH\=IA,IH\=IB,IH\=IC,IH\=ID,IH\=IE,IH\=IF,IH\=IG,IH\=AH,IH\=BH,IH\=CH,IH\=DH,IH\=EH,IH\=FH,IH\=GH,IH\=HH,IH\=GG,IH\=HG,IH\=GI,IH\=HI,
    (Length>80->(sub_atom(Sample, 80,1,_,IIE),not(empty(IIE))->II=IIE;num(II));num(II)),
    II\=IA,II\=IB,II\=IC,II\=ID,II\=IE,II\=IF,II\=IG,II\=IH,II\=AI,II\=BI,II\=CI,II\=DI,II\=EI,II\=FI,II\=GI,II\=HI,II\=AA,II\=BB,II\=CC,II\=DD,II\=EE,II\=FF,II\=GG,II\=HH,II\=HG,II\=GH,
    
    write("true").
