empty('x').
num('a').
num('b').
num('c').
num('d').
num('e').
num('f').
num('g').
num('h').
num('i').
atom_list_concat([H|T], Cat):-
    atom_list_concat(H,T,Cat).
atom_list_concat(Cat,[],Cat).
atom_list_concat(A,[H|T],Cat) :-
    atom_concat(A,H,ACat),
    atom_list_concat(ACat,T,Cat).
main([_|H]):-
    write("Input:<"),
    write(H),
    write(">Answer:<"),
    (H=[Arg|_],solver(Arg);write("false")),
    write(">").

solver(Sample) :-
    (not(atom(Sample))->fail;atom_length(Sample,Length)),
    (sub_atom(Sample, 0,1,_,AAE)->((Length>0,not(empty(AAE)))->AA=AAE;num(AA));num(AA)),
    
    (sub_atom(Sample, 1,1,_,ABE)->((Length>1,not(empty(ABE)))->AB=ABE;num(AB));num(AB)),
    AB\=AA,
    (sub_atom(Sample, 2,1,_,ACE)->((Length>2,not(empty(ACE)))->AC=ACE;num(AC));num(AC)),
    AC\=AA,AC\=AB,
    (sub_atom(Sample, 3,1,_,ADE)->((Length>3,not(empty(ADE)))->AD=ADE;num(AD));num(AD)),
    AD\=AA,AD\=AB,AD\=AC,
    (sub_atom(Sample, 4,1,_,AEE)->((Length>4,not(empty(AEE)))->AE=AEE;num(AE));num(AE)),
    AE\=AA,AE\=AB,AE\=AC,AE\=AD,
    (sub_atom(Sample, 5,1,_,AFE)->((Length>5,not(empty(AFE)))->AF=AFE;num(AF));num(AF)),
    AF\=AA,AF\=AB,AF\=AC,AF\=AD,AF\=AE,
    (sub_atom(Sample, 6,1,_,AGE)->((Length>6,not(empty(AGE)))->AG=AGE;num(AG));num(AG)),
    AG\=AA,AG\=AB,AG\=AC,AG\=AD,AG\=AE,AG\=AF,
    (sub_atom(Sample, 7,1,_,AHE)->((Length>7,not(empty(AHE)))->AH=AHE;num(AH));num(AH)),
    AH\=AA,AH\=AB,AH\=AC,AH\=AD,AH\=AE,AH\=AF,AH\=AG,
    (sub_atom(Sample, 8,1,_,AIE)->((Length>8,not(empty(AIE)))->AI=AIE;num(AI));num(AI)),
    AI\=AA,AI\=AB,AI\=AC,AI\=AD,AI\=AE,AI\=AF,AI\=AG,AI\=AH,
    
    (sub_atom(Sample, 9,1,_,BAE)->((Length>9,not(empty(BAE)))->BA=BAE;num(BA));num(BA)),
    BA\=AA,BA\=AB,BA\=AC,
    (sub_atom(Sample, 10,1,_,BBE)->((Length>10,not(empty(BBE)))->BB=BBE;num(BB));num(BB)),
    BB\=BA,BB\=AB,BB\=AA,BB\=AC,
    (sub_atom(Sample, 11,1,_,BCE)->((Length>11,not(empty(BCE)))->BC=BCE;num(BC));num(BC)),
    BC\=BA,BC\=BB,BC\=AC,BC\=AA,BC\=AB,
    (sub_atom(Sample, 12,1,_,BDE)->((Length>12,not(empty(BDE)))->BD=BDE;num(BD));num(BD)),
    BD\=BA,BD\=BB,BD\=BC,BD\=AD,BD\=AE,BD\=AF,
    (sub_atom(Sample, 13,1,_,BEE)->((Length>13,not(empty(BEE)))->BE=BEE;num(BE));num(BE)),
    BE\=BA,BE\=BB,BE\=BC,BE\=BD,BE\=AE,BE\=AD,BE\=AF,
    (sub_atom(Sample, 14,1,_,BFE)->((Length>14,not(empty(BFE)))->BF=BFE;num(BF));num(BF)),
    BF\=BA,BF\=BB,BF\=BC,BF\=BD,BF\=BE,BF\=AF,BF\=AD,BF\=AE,
    (sub_atom(Sample, 15,1,_,BGE)->((Length>15,not(empty(BGE)))->BG=BGE;num(BG));num(BG)),
    BG\=BA,BG\=BB,BG\=BC,BG\=BD,BG\=BE,BG\=BF,BG\=AG,BG\=AH,BG\=AI,
    (sub_atom(Sample, 16,1,_,BHE)->((Length>16,not(empty(BHE)))->BH=BHE;num(BH));num(BH)),
    BH\=BA,BH\=BB,BH\=BC,BH\=BD,BH\=BE,BH\=BF,BH\=BG,BH\=AH,BH\=AI,BH\=AG,
    (sub_atom(Sample, 17,1,_,BIE)->((Length>17,not(empty(BIE)))->BI=BIE;num(BI));num(BI)),
    BI\=BA,BI\=BB,BI\=BC,BI\=BD,BI\=BE,BI\=BF,BI\=BG,BI\=BH,BI\=AI,BI\=AG,BI\=AH,
    
    (sub_atom(Sample, 18,1,_,CAE)->((Length>18,not(empty(CAE)))->CA=CAE;num(CA));num(CA)),
    CA\=AA,CA\=BA,CA\=AB,CA\=BB,CA\=AC,CA\=BC,
    (sub_atom(Sample, 19,1,_,CBE)->((Length>19,not(empty(CBE)))->CB=CBE;num(CB));num(CB)),
    CB\=CA,CB\=AB,CB\=BB,CB\=AA,CB\=BA,CB\=AC,CB\=BC,
    (sub_atom(Sample, 20,1,_,CCE)->((Length>20,not(empty(CCE)))->CC=CCE;num(CC));num(CC)),
    CC\=CA,CC\=CB,CC\=AC,CC\=BC,CC\=AA,CC\=BB,CC\=BA,CC\=AB,
    (sub_atom(Sample, 21,1,_,CDE)->((Length>21,not(empty(CDE)))->CD=CDE;num(CD));num(CD)),
    CD\=CA,CD\=CB,CD\=CC,CD\=AD,CD\=BD,CD\=AE,CD\=BE,CD\=AF,CD\=BF,
    (sub_atom(Sample, 22,1,_,CEE)->((Length>22,not(empty(CEE)))->CE=CEE;num(CE));num(CE)),
    CE\=CA,CE\=CB,CE\=CC,CE\=CD,CE\=AE,CE\=BE,CE\=AD,CE\=BD,CE\=AF,CE\=BF,
    (sub_atom(Sample, 23,1,_,CFE)->((Length>23,not(empty(CFE)))->CF=CFE;num(CF));num(CF)),
    CF\=CA,CF\=CB,CF\=CC,CF\=CD,CF\=CE,CF\=AF,CF\=BF,CF\=AD,CF\=BD,CF\=AE,CF\=BE,
    (sub_atom(Sample, 24,1,_,CGE)->((Length>24,not(empty(CGE)))->CG=CGE;num(CG));num(CG)),
    CG\=CA,CG\=CB,CG\=CC,CG\=CD,CG\=CE,CG\=CF,CG\=AG,CG\=BG,CG\=BH,CG\=AI,CG\=AH,CG\=BI,
    (sub_atom(Sample, 25,1,_,CHE)->((Length>25,not(empty(CHE)))->CH=CHE;num(CH));num(CH)),
    CH\=CA,CH\=CB,CH\=CC,CH\=CD,CH\=CE,CH\=CF,CH\=CG,CH\=AH,CH\=BH,CH\=AG,CH\=BG,CH\=AI,CH\=BI,
    (sub_atom(Sample, 26,1,_,CIE)->((Length>26,not(empty(CIE)))->CI=CIE;num(CI));num(CI)),
    CI\=CA,CI\=CB,CI\=CC,CI\=CD,CI\=CE,CI\=CF,CI\=CG,CI\=CH,CI\=AI,CI\=BI,CI\=AG,CI\=BG,CI\=AH,CI\=BH,
    
    (sub_atom(Sample, 27,1,_,DAE)->((Length>27,not(empty(DAE)))->DA=DAE;num(DA));num(DA)),
    DA\=AA,DA\=BA,DA\=CA,
    (sub_atom(Sample, 28,1,_,DBE)->((Length>28,not(empty(DBE)))->DB=DBE;num(DB));num(DB)),
    DB\=DA,DB\=AB,DB\=BB,DB\=CB,
    (sub_atom(Sample, 29,1,_,DCE)->((Length>29,not(empty(DCE)))->DC=DCE;num(DC));num(DC)),
    DC\=DA,DC\=DB,DC\=AC,DC\=BC,DC\=CC,
    (sub_atom(Sample, 30,1,_,DDE)->((Length>30,not(empty(DDE)))->DD=DDE;num(DD));num(DD)),
    DD\=DA,DD\=DB,DD\=DC,DD\=AD,DD\=BD,DD\=CD,DD\=AA,DD\=BB,DD\=CC,
    (sub_atom(Sample, 31,1,_,DEE)->((Length>31,not(empty(DEE)))->DE=DEE;num(DE));num(DE)),
    DE\=DA,DE\=DB,DE\=DC,DE\=DD,DE\=AE,DE\=BE,DE\=CE,
    (sub_atom(Sample, 32,1,_,DFE)->((Length>32,not(empty(DFE)))->DF=DFE;num(DF));num(DF)),
    DF\=DA,DF\=DB,DF\=DC,DF\=DD,DF\=DE,DF\=AF,DF\=BF,DF\=CF,DF\=CG,DF\=BH,DF\=AI,
    (sub_atom(Sample, 33,1,_,DGE)->((Length>33,not(empty(DGE)))->DG=DGE;num(DG));num(DG)),
    DG\=DA,DG\=DB,DG\=DC,DG\=DD,DG\=DE,DG\=DF,DG\=AG,DG\=BG,DG\=CG,
    (sub_atom(Sample, 34,1,_,DHE)->((Length>34,not(empty(DHE)))->DH=DHE;num(DH));num(DH)),
    DH\=DA,DH\=DB,DH\=DC,DH\=DD,DH\=DE,DH\=DF,DH\=DG,DH\=AH,DH\=BH,DH\=CH,
    (sub_atom(Sample, 35,1,_,DIE)->((Length>35,not(empty(DIE)))->DI=DIE;num(DI));num(DI)),
    DI\=DA,DI\=DB,DI\=DC,DI\=DD,DI\=DE,DI\=DF,DI\=DG,DI\=DH,DI\=AI,DI\=BI,DI\=CI,
    
    (sub_atom(Sample, 36,1,_,EAE)->((Length>36,not(empty(EAE)))->EA=EAE;num(EA));num(EA)),
    EA\=AA,EA\=BA,EA\=CA,EA\=DA,EA\=DB,EA\=DC,
    (sub_atom(Sample, 37,1,_,EBE)->((Length>37,not(empty(EBE)))->EB=EBE;num(EB));num(EB)),
    EB\=EA,EB\=AB,EB\=BB,EB\=CB,EB\=DB,EB\=DA,EB\=DC,
    (sub_atom(Sample, 38,1,_,ECE)->((Length>38,not(empty(ECE)))->EC=ECE;num(EC));num(EC)),
    EC\=EA,EC\=EB,EC\=AC,EC\=BC,EC\=CC,EC\=DC,EC\=DA,EC\=DB,
    (sub_atom(Sample, 39,1,_,EDE)->((Length>39,not(empty(EDE)))->ED=EDE;num(ED));num(ED)),
    ED\=EA,ED\=EB,ED\=EC,ED\=AD,ED\=BD,ED\=CD,ED\=DD,ED\=DE,ED\=DF,
    (sub_atom(Sample, 40,1,_,EEE)->((Length>40,not(empty(EEE)))->EE=EEE;num(EE));num(EE)),
    EE\=EA,EE\=EB,EE\=EC,EE\=ED,EE\=AE,EE\=BE,EE\=CE,EE\=DE,EE\=AA,EE\=BB,EE\=CC,EE\=DD,EE\=DF,EE\=CG,EE\=BH,EE\=AI,
    (sub_atom(Sample, 41,1,_,EFE)->((Length>41,not(empty(EFE)))->EF=EFE;num(EF));num(EF)),
    EF\=EA,EF\=EB,EF\=EC,EF\=ED,EF\=EE,EF\=AF,EF\=BF,EF\=CF,EF\=DF,EF\=DD,EF\=DE,
    (sub_atom(Sample, 42,1,_,EGE)->((Length>42,not(empty(EGE)))->EG=EGE;num(EG));num(EG)),
    EG\=EA,EG\=EB,EG\=EC,EG\=ED,EG\=EE,EG\=EF,EG\=AG,EG\=BG,EG\=CG,EG\=DG,EG\=DH,EG\=DI,
    (sub_atom(Sample, 43,1,_,EHE)->((Length>43,not(empty(EHE)))->EH=EHE;num(EH));num(EH)),
    EH\=EA,EH\=EB,EH\=EC,EH\=ED,EH\=EE,EH\=EF,EH\=EG,EH\=AH,EH\=BH,EH\=CH,EH\=DH,EH\=DG,EH\=DI,
    (sub_atom(Sample, 44,1,_,EIE)->((Length>44,not(empty(EIE)))->EI=EIE;num(EI));num(EI)),
    EI\=EA,EI\=EB,EI\=EC,EI\=ED,EI\=EE,EI\=EF,EI\=EG,EI\=EH,EI\=AI,EI\=BI,EI\=CI,EI\=DI,EI\=DG,EI\=DH,
    
    (sub_atom(Sample, 45,1,_,FAE)->((Length>45,not(empty(FAE)))->FA=FAE;num(FA));num(FA)),
    FA\=AA,FA\=BA,FA\=CA,FA\=DA,FA\=EA,FA\=DB,FA\=EB,FA\=DC,FA\=EC,
    (sub_atom(Sample, 46,1,_,FBE)->((Length>46,not(empty(FBE)))->FB=FBE;num(FB));num(FB)),
    FB\=FA,FB\=AB,FB\=BB,FB\=CB,FB\=DB,FB\=EB,FB\=DA,FB\=EA,FB\=DC,FB\=EC,
    (sub_atom(Sample, 47,1,_,FCE)->((Length>47,not(empty(FCE)))->FC=FCE;num(FC));num(FC)),
    FC\=FA,FC\=FB,FC\=AC,FC\=BC,FC\=CC,FC\=DC,FC\=EC,FC\=DA,FC\=EA,FC\=DB,FC\=EB,
    (sub_atom(Sample, 48,1,_,FDE)->((Length>48,not(empty(FDE)))->FD=FDE;num(FD));num(FD)),
    FD\=FA,FD\=FB,FD\=FC,FD\=AD,FD\=BD,FD\=CD,FD\=DD,FD\=ED,FD\=EE,FD\=DF,FD\=CG,FD\=BH,FD\=AI,FD\=DE,FD\=EF,
    (sub_atom(Sample, 49,1,_,FEE)->((Length>49,not(empty(FEE)))->FE=FEE;num(FE));num(FE)),
    FE\=FA,FE\=FB,FE\=FC,FE\=FD,FE\=AE,FE\=BE,FE\=CE,FE\=DE,FE\=EE,FE\=DD,FE\=ED,FE\=DF,FE\=EF,
    (sub_atom(Sample, 50,1,_,FFE)->((Length>50,not(empty(FFE)))->FF=FFE;num(FF));num(FF)),
    FF\=FA,FF\=FB,FF\=FC,FF\=FD,FF\=FE,FF\=AF,FF\=BF,FF\=CF,FF\=DF,FF\=EF,FF\=AA,FF\=BB,FF\=CC,FF\=DD,FF\=EE,FF\=ED,FF\=DE,
    (sub_atom(Sample, 51,1,_,FGE)->((Length>51,not(empty(FGE)))->FG=FGE;num(FG));num(FG)),
    FG\=FA,FG\=FB,FG\=FC,FG\=FD,FG\=FE,FG\=FF,FG\=AG,FG\=BG,FG\=CG,FG\=DG,FG\=EG,FG\=DH,FG\=EH,FG\=DI,FG\=EI,
    (sub_atom(Sample, 52,1,_,FHE)->((Length>52,not(empty(FHE)))->FH=FHE;num(FH));num(FH)),
    FH\=FA,FH\=FB,FH\=FC,FH\=FD,FH\=FE,FH\=FF,FH\=FG,FH\=AH,FH\=BH,FH\=CH,FH\=DH,FH\=EH,FH\=DG,FH\=EG,FH\=DI,FH\=EI,
    (sub_atom(Sample, 53,1,_,FIE)->((Length>53,not(empty(FIE)))->FI=FIE;num(FI));num(FI)),
    FI\=FA,FI\=FB,FI\=FC,FI\=FD,FI\=FE,FI\=FF,FI\=FG,FI\=FH,FI\=AI,FI\=BI,FI\=CI,FI\=DI,FI\=EI,FI\=DG,FI\=EG,FI\=DH,FI\=EH,
    
    (sub_atom(Sample, 54,1,_,GAE)->((Length>54,not(empty(GAE)))->GA=GAE;num(GA));num(GA)),
    GA\=AA,GA\=BA,GA\=CA,GA\=DA,GA\=EA,GA\=FA,
    (sub_atom(Sample, 55,1,_,GBE)->((Length>55,not(empty(GBE)))->GB=GBE;num(GB));num(GB)),
    GB\=GA,GB\=AB,GB\=BB,GB\=CB,GB\=DB,GB\=EB,GB\=FB,
    (sub_atom(Sample, 56,1,_,GCE)->((Length>56,not(empty(GCE)))->GC=GCE;num(GC));num(GC)),
    GC\=GA,GC\=GB,GC\=AC,GC\=BC,GC\=CC,GC\=DC,GC\=EC,GC\=FC,GC\=FD,GC\=EE,GC\=DF,GC\=CG,GC\=BH,GC\=AI,
    (sub_atom(Sample, 57,1,_,GDE)->((Length>57,not(empty(GDE)))->GD=GDE;num(GD));num(GD)),
    GD\=GA,GD\=GB,GD\=GC,GD\=AD,GD\=BD,GD\=CD,GD\=DD,GD\=ED,GD\=FD,
    (sub_atom(Sample, 58,1,_,GEE)->((Length>58,not(empty(GEE)))->GE=GEE;num(GE));num(GE)),
    GE\=GA,GE\=GB,GE\=GC,GE\=GD,GE\=AE,GE\=BE,GE\=CE,GE\=DE,GE\=EE,GE\=FE,
    (sub_atom(Sample, 59,1,_,GFE)->((Length>59,not(empty(GFE)))->GF=GFE;num(GF));num(GF)),
    GF\=GA,GF\=GB,GF\=GC,GF\=GD,GF\=GE,GF\=AF,GF\=BF,GF\=CF,GF\=DF,GF\=EF,GF\=FF,
    (sub_atom(Sample, 60,1,_,GGE)->((Length>60,not(empty(GGE)))->GG=GGE;num(GG));num(GG)),
    GG\=GA,GG\=GB,GG\=GC,GG\=GD,GG\=GE,GG\=GF,GG\=AG,GG\=BG,GG\=CG,GG\=DG,GG\=EG,GG\=FG,GG\=AA,GG\=BB,GG\=CC,GG\=DD,GG\=EE,GG\=FF,
    (sub_atom(Sample, 61,1,_,GHE)->((Length>61,not(empty(GHE)))->GH=GHE;num(GH));num(GH)),
    GH\=GA,GH\=GB,GH\=GC,GH\=GD,GH\=GE,GH\=GF,GH\=GG,GH\=AH,GH\=BH,GH\=CH,GH\=DH,GH\=EH,GH\=FH,
    (sub_atom(Sample, 62,1,_,GIE)->((Length>62,not(empty(GIE)))->GI=GIE;num(GI));num(GI)),
    GI\=GA,GI\=GB,GI\=GC,GI\=GD,GI\=GE,GI\=GF,GI\=GG,GI\=GH,GI\=AI,GI\=BI,GI\=CI,GI\=DI,GI\=EI,GI\=FI,
    
    (sub_atom(Sample, 63,1,_,HAE)->((Length>63,not(empty(HAE)))->HA=HAE;num(HA));num(HA)),
    HA\=AA,HA\=BA,HA\=CA,HA\=DA,HA\=EA,HA\=FA,HA\=GA,HA\=GB,HA\=GC,
    (sub_atom(Sample, 64,1,_,HBE)->((Length>64,not(empty(HBE)))->HB=HBE;num(HB));num(HB)),
    HB\=HA,HB\=AB,HB\=BB,HB\=CB,HB\=DB,HB\=EB,HB\=FB,HB\=GB,HB\=GC,HB\=FD,HB\=EE,HB\=DF,HB\=CG,HB\=BH,HB\=AI,HB\=GA,
    (sub_atom(Sample, 65,1,_,HCE)->((Length>65,not(empty(HCE)))->HC=HCE;num(HC));num(HC)),
    HC\=HA,HC\=HB,HC\=AC,HC\=BC,HC\=CC,HC\=DC,HC\=EC,HC\=FC,HC\=GC,HC\=GA,HC\=GB,
    (sub_atom(Sample, 66,1,_,HDE)->((Length>66,not(empty(HDE)))->HD=HDE;num(HD));num(HD)),
    HD\=HA,HD\=HB,HD\=HC,HD\=AD,HD\=BD,HD\=CD,HD\=DD,HD\=ED,HD\=FD,HD\=GD,HD\=GE,HD\=GF,
    (sub_atom(Sample, 67,1,_,HEE)->((Length>67,not(empty(HEE)))->HE=HEE;num(HE));num(HE)),
    HE\=HA,HE\=HB,HE\=HC,HE\=HD,HE\=AE,HE\=BE,HE\=CE,HE\=DE,HE\=EE,HE\=FE,HE\=GE,HE\=GD,HE\=GF,
    (sub_atom(Sample, 68,1,_,HFE)->((Length>68,not(empty(HFE)))->HF=HFE;num(HF));num(HF)),
    HF\=HA,HF\=HB,HF\=HC,HF\=HD,HF\=HE,HF\=AF,HF\=BF,HF\=CF,HF\=DF,HF\=EF,HF\=FF,HF\=GF,HF\=GD,HF\=GE,
    (sub_atom(Sample, 69,1,_,HGE)->((Length>69,not(empty(HGE)))->HG=HGE;num(HG));num(HG)),
    HG\=HA,HG\=HB,HG\=HC,HG\=HD,HG\=HE,HG\=HF,HG\=AG,HG\=BG,HG\=CG,HG\=DG,HG\=EG,HG\=FG,HG\=GG,HG\=GH,HG\=GI,
    (sub_atom(Sample, 70,1,_,HHE)->((Length>70,not(empty(HHE)))->HH=HHE;num(HH));num(HH)),
    HH\=HA,HH\=HB,HH\=HC,HH\=HD,HH\=HE,HH\=HF,HH\=HG,HH\=AH,HH\=BH,HH\=CH,HH\=DH,HH\=EH,HH\=FH,HH\=GH,HH\=AA,HH\=BB,HH\=CC,HH\=DD,HH\=EE,HH\=FF,HH\=GG,HH\=GI,
    (sub_atom(Sample, 71,1,_,HIE)->((Length>71,not(empty(HIE)))->HI=HIE;num(HI));num(HI)),
    HI\=HA,HI\=HB,HI\=HC,HI\=HD,HI\=HE,HI\=HF,HI\=HG,HI\=HH,HI\=AI,HI\=BI,HI\=CI,HI\=DI,HI\=EI,HI\=FI,HI\=GI,HI\=GG,HI\=GH,
    
    (sub_atom(Sample, 72,1,_,IAE)->((Length>72,not(empty(IAE)))->IA=IAE;num(IA));num(IA)),
    IA\=AA,IA\=BA,IA\=CA,IA\=DA,IA\=EA,IA\=FA,IA\=GA,IA\=HA,IA\=HB,IA\=GC,IA\=FD,IA\=EE,IA\=DF,IA\=CG,IA\=BH,IA\=AI,IA\=GB,IA\=HC,
    (sub_atom(Sample, 73,1,_,IBE)->((Length>73,not(empty(IBE)))->IB=IBE;num(IB));num(IB)),
    IB\=IA,IB\=AB,IB\=BB,IB\=CB,IB\=DB,IB\=EB,IB\=FB,IB\=GB,IB\=HB,IB\=GA,IB\=HA,IB\=GC,IB\=HC,
    (sub_atom(Sample, 74,1,_,ICE)->((Length>74,not(empty(ICE)))->IC=ICE;num(IC));num(IC)),
    IC\=IA,IC\=IB,IC\=AC,IC\=BC,IC\=CC,IC\=DC,IC\=EC,IC\=FC,IC\=GC,IC\=HC,IC\=GA,IC\=HA,IC\=GB,IC\=HB,
    (sub_atom(Sample, 75,1,_,IDE)->((Length>75,not(empty(IDE)))->ID=IDE;num(ID));num(ID)),
    ID\=IA,ID\=IB,ID\=IC,ID\=AD,ID\=BD,ID\=CD,ID\=DD,ID\=ED,ID\=FD,ID\=GD,ID\=HD,ID\=GE,ID\=HE,ID\=GF,ID\=HF,
    (sub_atom(Sample, 76,1,_,IEE)->((Length>76,not(empty(IEE)))->IE=IEE;num(IE));num(IE)),
    IE\=IA,IE\=IB,IE\=IC,IE\=ID,IE\=AE,IE\=BE,IE\=CE,IE\=DE,IE\=EE,IE\=FE,IE\=GE,IE\=HE,IE\=GD,IE\=HD,IE\=GF,IE\=HF,
    (sub_atom(Sample, 77,1,_,IFE)->((Length>77,not(empty(IFE)))->IF=IFE;num(IF));num(IF)),
    IF\=IA,IF\=IB,IF\=IC,IF\=ID,IF\=IE,IF\=AF,IF\=BF,IF\=CF,IF\=DF,IF\=EF,IF\=FF,IF\=GF,IF\=HF,IF\=GD,IF\=HD,IF\=GE,IF\=HE,
    (sub_atom(Sample, 78,1,_,IGE)->((Length>78,not(empty(IGE)))->IG=IGE;num(IG));num(IG)),
    IG\=IA,IG\=IB,IG\=IC,IG\=ID,IG\=IE,IG\=IF,IG\=AG,IG\=BG,IG\=CG,IG\=DG,IG\=EG,IG\=FG,IG\=GG,IG\=HG,IG\=GH,IG\=HH,IG\=GI,IG\=HI,
    (sub_atom(Sample, 79,1,_,IHE)->((Length>79,not(empty(IHE)))->IH=IHE;num(IH));num(IH)),
    IH\=IA,IH\=IB,IH\=IC,IH\=ID,IH\=IE,IH\=IF,IH\=IG,IH\=AH,IH\=BH,IH\=CH,IH\=DH,IH\=EH,IH\=FH,IH\=GH,IH\=HH,IH\=GG,IH\=HG,IH\=GI,IH\=HI,
    (sub_atom(Sample, 80,1,_,IIE)->((Length>80,not(empty(IIE)))->II=IIE;num(II));num(II)),
    II\=IA,II\=IB,II\=IC,II\=ID,II\=IE,II\=IF,II\=IG,II\=IH,II\=AI,II\=BI,II\=CI,II\=DI,II\=EI,II\=FI,II\=GI,II\=HI,II\=AA,II\=BB,II\=CC,II\=DD,II\=EE,II\=FF,II\=GG,II\=HH,II\=HG,II\=GH,
    
    write("true").